[user]
foreground=255
background=31

[cwd]
foreground=255
background=241

[git]
foreground=255
background=238

[exit-code]
foreground=255
background=88

[virtual-environment]
foreground=255
background=104

[ssh]
foreground=255
background=208

[time]
foreground=255
background=31
