[user]
foreground=15
background=4

[cwd]
foreground=15
background=8

[git]
foreground=15
background=0

[exit-code]
foreground=15
background=1

[virtual-environment]
foreground=15
background=5

[ssh]
foreground=15
background=9

[time]
foreground=15
background=4
