[user]
foreground=229
background=66

[cwd]
foreground=229
background=241

[git]
foreground=229
background=237

[exit-code]
foreground=229
background=124

[virtual-environment]
foreground=229
background=132

[ssh]
foreground=229
background=166

[time]
foreground=229
background=66
